Repository RCDD-202110-TUR-BEW/backend-capstone-turkey-paying-it-forward, pull requests merged in 2022-03, with the labels that each got.

#58 Fix/item owner assignment
  src/controllers/__tests__/item.test.js
  src/controllers/item.js
Labels: bug

#59 Feat/add populate to queries
  src/controllers/__tests__/item.test.js
  src/controllers/auth.js
  src/controllers/item.js
  src/controllers/user.js
Labels: enhancement

#50 Request auth middleware
  src/controllers/__tests__/request.test.js
  src/middlewares/__tests__/request-authorization.test.js
  src/middlewares/request-authorization.js
  src/routers/request.js
Labels: enhancement

#60 Add donate item functionality
  src/controllers/__tests__/item.test.js
  src/controllers/item.js
  src/middlewares/item-authorization.js
  src/routers/item.js
Labels: enhancement

#52 Add rating endpoints
  src/controllers/__tests__/user.test.js
  src/controllers/user.js
  src/middlewares/__tests__/item-authorization.test.js
  src/routers/user.js
Labels: enhancement

#61 add google signin button
  src/public/css/home.css
  src/views/home.ejs
Labels: enhancement

#44 Documentation
  package.json
  src/app.js
  src/controllers/auth.js
  src/swagger.json
  src/views/home.ejs
  yarn.lock
Labels: documentation

#51 Update readme
  README.md
  src/assets/database.png
  src/assets/frontend1.png
  src/assets/frontend2.png
  src/assets/frontend3.png
  src/assets/frontend4.png
  src/assets/frontend5.png
  src/assets/system.png
Labels: documentation

#62 add the view demo link
  README.md
  src/swagger.json
Labels: documentation
